#  _     _____ _ _ ____    _   _ _____ _____
# | |   |  ___/ / |___   |  | | ____|_   _|
# | |   | |_  | | | __) | |  | |  _|   | |
# | |___|  _| | | |/ __/ _| |  | |___  | |
# |_____|_|   |_|_|_____(_)_| _|_____| |_|

name: Auto Update Version CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  updateVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 使用 Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 检查 & 更新
        run: |
          echo "---------- MAIN ----------"
          echo ' 正在安装依赖...';
          npm i child_process;
          echo ' 正在执行更新脚本...';
          node ./script/autoUpdateVersion.js COMMIT="$(git rev-parse --short HEAD)" BRANCH="$(git rev-parse --abbrev-ref HEAD)";
          echo 'Auto Update Version DONE!';

      - name: 获取 GIT 权限
        run: |
          git config --global url."https://fuicou:${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.email "lf@furry.icu"
          git config --global user.name "fuicou"

      - name: 推送
        run: |
          sreid=$(git rev-parse --short HEAD)
          rename=$(git log --pretty=format:"%an" $reid -1)
          BGV=$(node -e "console.log(require('./package.json').version.split('-')[0])");
          git add . && git commit -m "🚀 V$BGV ↑ [$rename - $sreid]" && git push -u;
          echo ' 更新成功！'; \
          echo "---------- MAIN ----------"
          echo ' 作业完毕。'
